config/routes.rb
Rails.application.routes.draw do
  #get 'albums/index'
  #get 'albums/new'
  #get 'albums/showedit'
  #get 'songs/new'
  #get 'songs/edit'
  #get 'artists/index'
  #get 'artists/show'
  #get 'artists/new'
  #get 'artists/edit'
  root to: 'artists#index'
  resources :artists, only: [:index, :show, :new, :create] do
    resources :songs, only: [:new, :create]
  end
  resources :songs, only: [:destroy]
  # resources :albums
end

app/models/album.rb
class Album < ApplicationRecord
  #GENRES = ['Britpop', '90s', 'Mancunian', 'Madchester', 'Progressive', 'Punk']
  has_one_attached :photo
  has_many :songs
  validates :name, presence: true
  #validates :genre, inclusion: { in: GENRES }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_one_attached :photo
  has_many :songs, dependent: :destroy
  has_many :albums, through: :songs
  #YEARS = (1..70)
  validates :name, presence: true, uniqueness: true
  #validates :years_active, inclusion: { in: YEARS }
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  belongs_to :album
  LENGTH = (0..10)
  validates :name, presence: true, uniqueness: true
  validates :minutes, inclusion: {in: LENGTH }
  # validates :album, uniqueness: { scope: :artist }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show]

  def index
    @artists = Artist.all
  end

  def show
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)
    # raise
    if @artist.save
      redirect_to artist_path(@artist)
    else
      render :new
    end
  end

  # def update
  #   @artist.update(artist_params)
  #   if @artist.save
  #     redirect_to artist_path(@artist)
  #   else
  #     render :new
  #   end
  # end

  private

  def set_artist
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:name, :years_active, :separated, :photo)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:edit, :update, :destroy]

  def new
    @artist = Artist.find(params[:artist_id])
    @song = Song.new
  end

  def create
    @artist = Artist.find(params[:artist_id])
    @song = Song.new(song_params)
    @song.artist = @artist
    if @song.save
      redirect_to artist_path(@artist)
    else
      render :new
    end
  end

  # def edit
  # end

  # def update
  #   @song.update(song_params)
  #   if @song.save
  #     redirect_to song_path(@song)
  #   else
  #     render :edit
  #   end
  # end

  def destroy
    @song.destroy
    redirect_to artist_path(@song.artist)
  end

  private

  def set_song
    @song = Song.find(params[:id])
  end

  def song_params
    params.require(:song).permit(:name, :minutes, :album_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/index.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="/artists">
    <img src="https://www.publicdomainpictures.net/pictures/40000/velka/union-jack-flag-1365882581V0R.jpg" />
  </a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a><%= link_to 'Add an artist', new_artist_path(@artist) %></a>
      </li>
    </ul>
  </div>
</div>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://cdn.onebauer.media/one/media/5e00/e350/6a79/a373/b5e5/b37b/1990s_albums.jpg);">
  <div class="container">
    <h1><strong>Create your own playlist!</strong></h1>
  </div>
</div>

<div class="container">
  <div class="cards">
    <ul>
      <% @artists.each do |artist| %>
        <li><strong><%= link_to artist.name, artist_path(artist) %></strong></li>
           <%# link_to 'Edit', edit_artist_path(artist) %>
      <% end %>
    </ul>
  </div>
</div>

app/views/artists/new.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="/artists">
    <img src="https://www.publicdomainpictures.net/pictures/40000/velka/union-jack-flag-1365882581V0R.jpg" />
  </a>
</div>

<div class="song-container">
  <div class="song-info">
    <h1>Add a new artist</h1>

    <%= simple_form_for(@artist) do |f| %>
        <%= f.input :name %>
        <%= f.input :years_active %>
        <%= f.input :separated, as: :boolean, checked_value: true, unchecked_value: false %>
        <%= f.input :photo, as: :file %>
        <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/artists/show.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="/artists">
    <img src="https://www.publicdomainpictures.net/pictures/40000/velka/union-jack-flag-1365882581V0R.jpg" />
  </a>
</div>

<div class="d-flex slack-container">
  <div class="conversations-sidebar">
    <div class="chat-section">
      <div class="chat-section-header">
        <%= link_to 'Home', artists_path %>
      </div>
      <div class="channel">
        <%= link_to 'Add an artist', new_artist_path(@artist) %>
      </div>
      <div class="channel">
        <%= link_to 'Add a new song', new_artist_song_path(@artist) %>
      </div>
    </div>
  </div>
  <div class="chat-container">
    <div class="chat-header">
      <h1><strong>Playlist</strong></h1>
    </div>

    <div class="artist-info">
      <h3><%= @artist.name %></h3>
      <% if @artist.separated %>
        <h4><%= @artist.years_active %> years active (already separated)</h4>
      <% else %>
        <h4><%= @artist.years_active %> years active (still active)</h4>
      <% end %>
    </div>
    <div class="chat-conversations">
      <div class="message">
        <div class="card-product-photo">
          <%= cl_image_tag @artist.photo.key, height: 350, width: 350, crop: :fill %>
        </div>
        <div class="message-content">
          <ul>
            <% i = 1 %>
            <% @artist.songs.each do |song| %>
              <strong><%= i %> -   <%= song.name %></strong> from <strong><%= song.album.name %></strong>
              <%# link_to song.album.name, album_path(@album) %>
                <li><%= link_to 'Watch a video in YouTube', "https://www.youtube.com/results?search_query=#{@artist.name} #{song.name}", target: :_blank %></li>
                <%# link_to 'Edit', edit_artist_song_path(song) %>
                <li><%= link_to 'Delete', song_path(song), method: :delete, data: { confirm: "Are you sure to delete #{song.name}?" } %></li>
              <% i += 1 %>
            <% end %>
          </ul>
        </div>
      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BritishRockDictionary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/songs/new.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="/artists">
    <img src="https://www.publicdomainpictures.net/pictures/40000/velka/union-jack-flag-1365882581V0R.jpg" />
  </a>
</div>

<div class="song-container">
  <div class="song-info">
    <h1>Add a new song</h1>

    <%= simple_form_for [@artist, @song] do |f| %>
      <%= f.input :name %>
      <%= f.input :minutes %>
      <%= f.association :album, input_html: { class: 'album' } %>
      <%= f.submit %>
    <% end %>
  </div>
</div>
<!-- need to change input_html -->